config/routes.rb
Rails.application.routes.draw do
  get "clients/:client_id/credit", to: "transactions#credit", as: 'credit_transaction'
  post "clients/:client_id/create_credit", to: "transactions#create_credit", as: 'create_credit_transaction'
  get "clients/:client_id/debit", to: "transactions#debit", as: 'debit_transaction'
  post "clients/:client_id/create_debit", to: "transactions#create_debit", as: 'create_debit_transaction'
  
  resources :clients do
    resources :transactions, only: [:index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "clients#index"
end

app/models/client.rb
class Client < ApplicationRecord
  validates :email, presence: true
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :name, uniqueness: true

  has_one :wallet, dependent: :destroy
  has_many :transactions

  scope :exclude, -> (*values) { 
    where(
      "#{table_name}.id NOT IN (?)",
        (
          values.compact.flatten.map { |e|
            if e.is_a?(Integer) 
              e
            else
              e.is_a?(self) ? e.id : raise("Element not the same type as #{self}.")
            end
          } << 0
        )
      )
    }

  def self.users
    where(type: 'User')
  end

  def self.teams
    where(type: 'Team')
  end

  def self.stocks
    where(type: 'Stock')
  end
  
  def user?
    type.eql?('User')
  end

  def team?
    type.eql?('Team')
  end

  def stock?
    type.eql?('Stock')
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
    @client = Client.find_by_id(params[:id])
    @user = Client.find_by_id(params[:id])
    @team = Client.find_by_id(params[:id])
    @stock = Client.find_by_id(params[:id])
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "#{@client.type} was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "#{@client.type} was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "#{@client.type} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find_by_id(params[:id])
      @show_client_text = "Show this #{@client.type}"
      @edit_client_text = "Edit this #{@client.type}"
    end

    # Only allow a list of trusted parameters through.

    def client_params
      params.require(:client).permit(:name, :email)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client.users %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= form.label :name %>
            <%= form.text_field :name %>
            <%= form.label :email %>
            <%= form.text_field :email %>
          <button type="submit" class="btn btn-primary mb-2">Update <%= client.type %></button>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/clients/edit.html.erb
<div class="col">
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to @show_client_text, [@client.becomes(User)] %> |
  <%= link_to "Back to clients", clients_path %>
</div>
</div>

app/views/clients/index.html.erb
<div class="col">
  <h1>Users</h1>

  <div id="users">
    <% @clients.users.each do |user| %>
      <%= render user %>
    <% end %>
  </div>
</div>
<div class="col">
  <h1>Teams</h1>

  <div id="teams">
    <% @clients.teams.each do |team| %>
      <%= render team %>
    <% end %>
  </div>
</div>
<div class="col">
  <h1>Stock</h1>

  <div id="teams">
    <% @clients.stocks.each do |stock| %>
      <%= render stock %>
    <% end %>
  </div>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<div class="col">
  <%= render @user %>

  <div>
    <%= link_to "Check client transactions", client_transactions_path(@user) %> |
    <%= link_to @edit_client_text, edit_client_path(@user) %> |
    <%= link_to "Back to clients", clients_path %>

  </div>
</div>