config/routes.rb
Rails.application.routes.draw do
  get "clients/:client_id/credit", to: "transactions#credit", as: 'credit_transaction'
  post "clients/:client_id/create_credit", to: "transactions#create_credit", as: 'create_credit_transaction'
  get "clients/:client_id/debit", to: "transactions#debit", as: 'debit_transaction'
  post "clients/:client_id/create_debit", to: "transactions#create_debit", as: 'create_debit_transaction'
  
  resources :clients do
    resources :transactions, only: [:index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "clients#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_client_transaction

  def index
    
  end

  def debit
    
  end

  def create_debit
    setup_debit_params(transaction_params)
    @transaction = Transaction.new(@params)

    if params[:debit][:amount].to_i < 0
      redirect_to client_transactions_path, notice: "#{@transaction.type} was failed, make sure you're using positive amount"
    else
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to client_transactions_path, notice: "#{@transaction.type} was successfully created." }
          format.json { render :show, status: :created, location: @transaction }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def setup_debit_params(params)
    @params = {
      client_id: params[:client_id],
      amount: ("#{params[:debit][:amount]}".to_i.abs * -1),
      type: 'Debit',
      sender_wallet_id: Client.find_by_id(params[:client_id]).wallet.id,
      receiver_wallet_id: Client.find_by_email(params[:client][:email]).wallet.id
    }
  end

  def credit

  end

  def create_credit
    setup_credit_params(transaction_params)
    @transaction = Transaction.new(@params)

    if params[:credit][:amount].to_i < 0
      redirect_to client_transactions_path, notice: "#{@transaction.type} was failed, make sure you're using positive amount"
    else
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to client_transactions_path, notice: "#{@transaction.type} was successfully created." }
          format.json { render :show, status: :created, location: @transaction }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def setup_credit_params(params)
    @params = {
      client_id: params[:client_id],
      amount: params[:credit][:amount],
      type: 'Credit',
      sender_wallet_id: nil,
      receiver_wallet_id: Client.find_by_id(params[:client_id]).wallet.id
    }
  end

  def new
    
  end

  def show
    puts "params.inspect: #{params.inspect}"
    puts "params[:type]: #{params[:type]}"
    @client = Client.find_by_id(params[:id])
    @user = Client.find_by_id(params[:id])
    @team = Client.find_by_id(params[:id])
    @stock = Client.find_by_id(params[:id])

    puts "@client.inspect: #{@client.inspect}"
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # POST /clients or /clients.json
  def create
    puts "transaction_params.inspect: #{transaction_params.inspect}"
    puts "params.inspect: #{params.inspect}"
    puts "transaction_params.permitted?: #{transaction_params.permitted?}"
    puts "params.permitted?: #{params.permitted?}"
    @client = Client.new(params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "#{@client.type} was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_transaction
      @client = Client.find_by_id(params[:client_id])
      @client_balance = Transaction.balance(@client.wallet)
      @client_debit   = Transaction.debit(@client.wallet)
      @client_credit  = Transaction.credit(@client.wallet)
    end

    # Only allow a list of trusted parameters through.

    def transaction_params
      params.permit(:client_id, debit: [:amount], credit: [:amount], client: [:email])
    end

end

app/views/transactions/_form.html.erb
<%= form_with(@transaction) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= form.label 'amount' %>
            <%= form.number_field :amount %>
            <%= form.label 'to' %>
            <%= select("clients", "id", Client.all.exclude(@client.id).collect {|p| [ p.name, p.email ] }, { include_blank: false }) %>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Send</button>
      </div>
    </div>
  </form>
<% end %>

app/views/transactions/credit.html.erb
<div class="col">
  <h1><%= @client.name %> Balance</h1>
  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= @client_balance %>
        </div>
      </div>
    </div>
  </form>
  <%= form_with scope: :credit, url: create_credit_transaction_path do |form| %>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
          <%= form.label 'amount' %>
          <%= form.number_field :amount %>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Send</button>
      </div>
    </div>
  <% end %>
  <%= link_to "Back to transactions", client_transactions_path %>
</div>

app/views/transactions/debit.html.erb
<div class="col">
  <h1><%= @client.name %> Balance</h1>
  <form>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
            <%= @client_balance %>
        </div>
      </div>
    </div>
  </form>
  <%= form_with scope: :debit, url: create_debit_transaction_path do |form| %>
    <div class="col  mb-2">
      <div class="card" style="width: 36rem;">
        <div class="card-body">
          <%= form.label 'amount' %>
          <%= form.number_field :amount %>
          <%= select("client", "email", Client.all.exclude(@client.id).collect {|p| [ p.name, p.email ] }, { include_blank: false }) %>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Send</button>
      </div>
    </div>
  <% end %>

  <%= link_to "Back to transactions", client_transactions_path %>
</div>

app/views/transactions/index.html.erb
<div class="col">
  <h1><%= @client.name%> Transactions</h1>
  <div class="col">
    <h1>Balance</h1>

    <div id="users">
      <p><%= @client_balance %></p>
    </div>
  </div>
  <div class="col">
    <h1>Credit</h1>

    <div id="teams">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Type</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
          </tr>
        </thead>
        <tbody>
          <% @client_credit.each do |credit| %>
            <%= render credit %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col">
    <h1>Debit</h1>

    <div id="teams">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Type</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
          </tr>
        </thead>
        <tbody>
          <% @client_debit.each do |debit| %>
            <%= render debit %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col">
    <%= link_to "Credit with #{@client.name}", credit_transaction_path %> |
    <%= link_to "Debit with #{@client.name}", debit_transaction_path %> |
    <%= link_to "Back to clients", clients_path %>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to transactions", client_transactions_path %>
</div>